# Generated by Django 2.0 on 2020-06-26 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user_id',
            new_name='user',
        ),
    ]
